### ISSUE TITLE
[ENHANCEMENT] Add a `.gitignore`

### ISSUE THREAD

**Issue by brodeuralexis** [dmccoystephenson/Tic-Tac-Toe-Against-Unintelligent-Computer-#1]
Hi Daniel, here from Reddit.

You might want to watch/read a few tutorials about git, it's an industry standard.

To whip up `.gitignore` files, there is this fabulous tool called [gitignore.io](https://www.gitignore.io/).

**Comment by swdgit** [comment]
second this. the .bin .classpath .project .settings should all remain on your computer and keep the codebase clean.

**Comment by brodeuralexis** [comment]
Fixed by PR #2
